services:
  frontend:
    image: kevloves/crud-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    mem_limit: 256m

  backend:
    image: kevloves/crud-backend:latest
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://admin:password@mongodb.example.com/crud-app
      - JWT_SECRET=myJWTsecret123
    mem_limit: 256m

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: